"""v0.3.0_initial

Revision ID: bedaa881e856
Revises: 
Create Date: 2026-05-15 20:43:51.337196
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bedaa881e856'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('marketing', 'legal', 'admin', name='userrole'), nullable=False),
    sa.Column('dept_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('material_type', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Enum('normal', 'urgent', 'extreme', name='materialpriority'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ai_reviewing', 'pending_legal', 'in_legal_review', 'approved', 'returned', name='materialstatus'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ai_risk_score', sa.Integer(), nullable=False),
    sa.Column('ai_result', sa.JSON(), nullable=False),
    sa.Column('legal_decision', sa.Enum('approved', 'returned', 'conditional', name='legaldecision'), nullable=True),
    sa.Column('legal_notes', sa.Text(), nullable=True),
    sa.Column('return_reasons', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_material_id'), 'reviews', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_material_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('materials')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
